// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOXMotwvkCq42t5sPeCA8thPgRn8N84Dg',
    appId: '1:719990573629:web:a5cfce6e4b584b739cf854',
    messagingSenderId: '719990573629',
    projectId: 'webrtc-live-test',
    authDomain: 'webrtc-live-test.firebaseapp.com',
    storageBucket: 'webrtc-live-test.appspot.com',
    measurementId: 'G-T6790F44D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tlj_iPWlF6foiataHEev5Cil7_vPPCg',
    appId: '1:719990573629:android:7bad8da6ee0147ff9cf854',
    messagingSenderId: '719990573629',
    projectId: 'webrtc-live-test',
    storageBucket: 'webrtc-live-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX5NFXjM1vSciKO-F9wWzSkkbalIreRtA',
    appId: '1:719990573629:ios:e761d946874609999cf854',
    messagingSenderId: '719990573629',
    projectId: 'webrtc-live-test',
    storageBucket: 'webrtc-live-test.appspot.com',
    iosClientId: '719990573629-i3d9go3kfn0i1gu6cddds6qg6cosanno.apps.googleusercontent.com',
    iosBundleId: 'com.kortobaa.webrtcTest',
  );
}
